apiVersion: v1
kind: Service
metadata:
  name: sdc-service-lb
spec:
  type: LoadBalancer
  ports:
  - port: 8083
    name: http
    protocol: TCP
    targetPort: http
  selector:
    app: sdc-with-pipeline