apiVersion: v1
kind: Service
metadata:
  name: sdc-pipeline-lb
spec:
  type: LoadBalancer
  ports:
  - port: 8084
    name: http
    protocol: TCP
    targetPort: 8000
  selector:
    app: sdc-with-pipeline